default_language_version:
  python: python3.10

# Disable checks of third-party code
exclude: third_party/

repos:
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      description: wemake-python-styleguide enforcement
      entry: flake8
      args: [ "--config=setup.cfg" ]
      language: python
      types: [ python ]
      additional_dependencies: [ wemake-python-styleguide>=0.19.2 ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: check-toml
      - id: check-yaml
        args:
          - '--unsafe'
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--skip-string-normalization", "--line-length=120"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML"]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.5.1
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-flake8
        additional_dependencies: [ flake8==6.1.0 ]
        args: ["--max-line-length=120"]
      - id: nbqa-mypy
        additional_dependencies: [ mypy==1.5.1 ]
        args: ["--ignore-missing-imports", "--follow-imports=skip"]
      - id: nbqa-black
        additional_dependencies: [ black==23.1.0 ]
        args: ["--skip-string-normalization", "--line-length=120"]
      - id: nbqa-isort
        additional_dependencies: [ isort==5.12.0 ]
        args: ["--profile=black", "--line-length=120"]
